using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		public partial class TBLTalisman : BGEntity
		{

			//=============================================================
			//||                   Generated by BansheeGz Code Generator ||
			//=============================================================

			public class Factory : BGEntity.EntityFactory
			{
				public BGEntity NewEntity(BGMetaEntity meta)
				{
					return new TBLTalisman(meta);
				}
				public BGEntity NewEntity(BGMetaEntity meta, BGId id)
				{
					return new TBLTalisman(meta, id);
				}
			}
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4979303619098737748,10003856562283416746));
					return _metaDefault;
				}
			}
			public static BansheeGz.BGDatabase.BGRepoEvents Events
			{
				get
				{
					return BGRepo.I.Events;
				}
			}
			private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
			public static int CountEntities
			{
				get
				{
					return MetaDefault.CountEntities;
				}
			}
			public System.String name
			{
				get
				{
					return _name[Index];
				}
				set
				{
					_name[Index] = value;
				}
			}
			public System.Single moveSpeed
			{
				get
				{
					return _moveSpeed[Index];
				}
				set
				{
					_moveSpeed[Index] = value;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5137404689476894540,9997574991049143191));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_moveSpeed;
			public static BansheeGz.BGDatabase.BGFieldFloat _moveSpeed
			{
				get
				{
					if(_ufle12jhs77_moveSpeed==null || _ufle12jhs77_moveSpeed.IsDeleted) _ufle12jhs77_moveSpeed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4933146661899666740,18195268792429218718));
					return _ufle12jhs77_moveSpeed;
				}
			}
			private static readonly TBLTalisman.Factory _factory1_PFS = new TBLTalisman.Factory();
			public TBLTalisman() : base(MetaDefault)
			{
			}
			public TBLTalisman(BGId id) : base(MetaDefault, id)
			{
			}
			public TBLTalisman(BGMetaEntity meta) : base(meta)
			{
			}
			public TBLTalisman(BGMetaEntity meta, BGId id) : base(meta, id)
			{
			}
			public static TBLTalisman FindEntity(Predicate<TBLTalisman> filter)
			{
				return MetaDefault.FindEntity(entity => filter==null || filter((TBLTalisman) entity)) as TBLTalisman;
			}
			public static List<TBLTalisman> FindEntities(Predicate<TBLTalisman> filter, List<TBLTalisman> result=null, Comparison<TBLTalisman> sort=null)
			{
				result = result ?? new List<TBLTalisman>();
				_find_Entities_Result.Clear();
				MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((TBLTalisman) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((TBLTalisman) e1, (TBLTalisman) e2));
				if (_find_Entities_Result.Count != 0)
				{
					for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((TBLTalisman) _find_Entities_Result[i]);
					_find_Entities_Result.Clear();
				}
				return result;
			}
			public static void ForEachEntity(Action<TBLTalisman> action, Predicate<TBLTalisman> filter=null, Comparison<TBLTalisman> sort=null)
			{
				MetaDefault.ForEachEntity(entity => action((TBLTalisman) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((TBLTalisman) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((TBLTalisman)e1,(TBLTalisman)e2));
			}
			public static TBLTalisman GetEntity(BGId entityId)
			{
				return (TBLTalisman) MetaDefault.GetEntity(entityId);
			}
			public static TBLTalisman GetEntity(int index)
			{
				return (TBLTalisman) MetaDefault[index];
			}
			public static TBLTalisman GetEntity(string entityName)
			{
				return (TBLTalisman) MetaDefault.GetEntity(entityName);
			}
			public static TBLTalisman NewEntity()
			{
				return (TBLTalisman) MetaDefault.NewEntity();
			}
		}

#pragma warning restore 414
