using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/TBLEnemyStatus")]
public partial class TBLEnemyStatus : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5678017057748086214,8502664407001919410));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public System.Single moveSpeed
	{
		get
		{
			return _moveSpeed[Entity.Index];
		}
		set
		{
			_moveSpeed[Entity.Index] = value;
		}
	}
	public System.Single minJumpHeight
	{
		get
		{
			return _minJumpHeight[Entity.Index];
		}
		set
		{
			_minJumpHeight[Entity.Index] = value;
		}
	}
	public System.Single maxJumpHeight
	{
		get
		{
			return _maxJumpHeight[Entity.Index];
		}
		set
		{
			_maxJumpHeight[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector2 MoveDetectStart
	{
		get
		{
			return _MoveDetectStart[Entity.Index];
		}
		set
		{
			_MoveDetectStart[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector2 MoveDetectEnd
	{
		get
		{
			return _MoveDetectEnd[Entity.Index];
		}
		set
		{
			_MoveDetectEnd[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector2 AttackDetectStart
	{
		get
		{
			return _AttackDetectStart[Entity.Index];
		}
		set
		{
			_AttackDetectStart[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector2 AttackDetectEnd
	{
		get
		{
			return _AttackDetectEnd[Entity.Index];
		}
		set
		{
			_AttackDetectEnd[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector2 platformCheckPos
	{
		get
		{
			return _platformCheckPos[Entity.Index];
		}
		set
		{
			_platformCheckPos[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4754389191886434300,16063906217628222391));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __moveSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _moveSpeed
	{
		get
		{
			if(__moveSpeed==null || __moveSpeed.IsDeleted) __moveSpeed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4914523001697751054,558437076329102489));
			return __moveSpeed;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __minJumpHeight;
	public static BansheeGz.BGDatabase.BGFieldFloat _minJumpHeight
	{
		get
		{
			if(__minJumpHeight==null || __minJumpHeight.IsDeleted) __minJumpHeight=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5539145356334836820,6711173540710739849));
			return __minJumpHeight;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __maxJumpHeight;
	public static BansheeGz.BGDatabase.BGFieldFloat _maxJumpHeight
	{
		get
		{
			if(__maxJumpHeight==null || __maxJumpHeight.IsDeleted) __maxJumpHeight=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5638697434986177724,16829224106945084057));
			return __maxJumpHeight;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector2 __MoveDetectStart;
	public static BansheeGz.BGDatabase.BGFieldVector2 _MoveDetectStart
	{
		get
		{
			if(__MoveDetectStart==null || __MoveDetectStart.IsDeleted) __MoveDetectStart=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(5747331735756656086,3320746928093716134));
			return __MoveDetectStart;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector2 __MoveDetectEnd;
	public static BansheeGz.BGDatabase.BGFieldVector2 _MoveDetectEnd
	{
		get
		{
			if(__MoveDetectEnd==null || __MoveDetectEnd.IsDeleted) __MoveDetectEnd=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(5075692337743546368,7559170699297928858));
			return __MoveDetectEnd;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector2 __AttackDetectStart;
	public static BansheeGz.BGDatabase.BGFieldVector2 _AttackDetectStart
	{
		get
		{
			if(__AttackDetectStart==null || __AttackDetectStart.IsDeleted) __AttackDetectStart=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4858391092339630745,16522775585135925419));
			return __AttackDetectStart;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector2 __AttackDetectEnd;
	public static BansheeGz.BGDatabase.BGFieldVector2 _AttackDetectEnd
	{
		get
		{
			if(__AttackDetectEnd==null || __AttackDetectEnd.IsDeleted) __AttackDetectEnd=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(5690934996591517823,6615302915134543521));
			return __AttackDetectEnd;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector2 __platformCheckPos;
	public static BansheeGz.BGDatabase.BGFieldVector2 _platformCheckPos
	{
		get
		{
			if(__platformCheckPos==null || __platformCheckPos.IsDeleted) __platformCheckPos=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(5061778677936757359,16005822572342414979));
			return __platformCheckPos;
		}
	}
}
